/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Main (void);
GtkWidget* create_Chooser (void);
GtkWidget* create_About (void);
GtkWidget* create_Properties (void);
GtkWidget* create_Message (void);
